# Generated by Django 6.0 on 2025-12-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('image_url', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'pets',
                'managed': False,
            },
        ),
    ]
