# Generated by Django 6.0 on 2025-12-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.IntegerField()),
                ('place', models.CharField(max_length=50)),
                ('text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('not_available', 'Not Available')], max_length=13)),
            ],
            options={
                'db_table': 'ads',
                'managed': False,
            },
        ),
    ]
